In [7]:
import pandas as pd
import numpy as np

In [8]:
consumption_data = pd.read_csv("https://drive.google.com/uc?id=1D9mWQJlp6n8eF7zr0hdTB1T03MWRXTWz")

In [9]:
consumption_data.head(5)

,iso_code,country,year,coal_prod_change_pct,coal_prod_change_twh,gas_prod_change_pct,gas_prod_change_twh,oil_prod_change_pct,oil_prod_change_twh,energy_cons_change_pct,...,solar_elec_per_capita,solar_energy_per_capita,gdp,wind_share_elec,wind_cons_change_pct,wind_share_energy,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_energy_per_capita
0,AFG,Afghanistan,1900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AFG,Afghanistan,1901,NaN,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AFG,Afghanistan,1902,NaN,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AFG,Afghanistan,1903,NaN,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AFG,Afghanistan,1904,NaN,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
cs = consumption_data[(consumption_data['country'].isin(['China', 'Japan', 'United States', 'South Africa', 'Mexico', 'United Kingdom'])) & (consumption_data['year'] >= 1980) & (consumption_data['year'] <= 2019)]
cols = [
     'country',
     'year',
     'coal_consumption',
     'coal_cons_per_capita',
     'fossil_fuel_consumption',
     'fossil_cons_per_capita',
     'gas_consumption',
     'gas_energy_per_capita',
     'hydro_consumption',
     'hydro_energy_per_capita',
     'nuclear_consumption',
     'nuclear_energy_per_capita',
     'oil_consumption',
     'oil_energy_per_capita',
     'primary_energy_consumption',
     'electricity_generation',
     'per_capita_electricity',
     'renewables_consumption',
     'renewables_energy_per_capita',
     'primary_energy_consumption',
     'energy_per_capita']
cs_wcols = cs[cols]

In [22]:
cs_wcols = cs_wcols.fillna(0)

In [23]:
cs_wcols.to_csv('data.csv')